/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.smarthome.am.shome.ide


/**
 * Use this class to register ide components.
 */
class ShomeIdeModule extends AbstractShomeIdeModule {
}
