/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.smarthome.am.shome


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ShomeStandaloneSetup extends ShomeStandaloneSetupGenerated {

	def static void doSetup() {
		new ShomeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
