/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.smarthome.am.shome.validation;

import fr.unice.polytech.si5.smarthome.am.shome.validation.AbstractShomeValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ShomeValidator extends AbstractShomeValidator {
}
