/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.smarthome.am.shome.ide;

import fr.unice.polytech.si5.smarthome.am.shome.ide.AbstractShomeIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ShomeIdeModule extends AbstractShomeIdeModule {
}
