/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.smarthome.am.shome.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.unice.polytech.si5.smarthome.am.shome.ShomeRuntimeModule;
import fr.unice.polytech.si5.smarthome.am.shome.ShomeStandaloneSetup;
import fr.unice.polytech.si5.smarthome.am.shome.ide.ShomeIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ShomeIdeSetup extends ShomeStandaloneSetup {
  @Override
  public Injector createInjector() {
    ShomeRuntimeModule _shomeRuntimeModule = new ShomeRuntimeModule();
    ShomeIdeModule _shomeIdeModule = new ShomeIdeModule();
    return Guice.createInjector(Modules2.mixin(_shomeRuntimeModule, _shomeIdeModule));
  }
}
