/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.smarthome.am.shome.ui.tests;

import com.google.inject.Injector;
import fr.unice.polytech.si5.smarthome.am.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ShomeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("fr.unice.polytech.si5.smarthome.am.shome.Shome");
	}

}
