/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.smarthome.am.shome.parser.antlr;

import com.google.inject.Inject;
import fr.unice.polytech.si5.smarthome.am.shome.parser.antlr.internal.InternalShomeParser;
import fr.unice.polytech.si5.smarthome.am.shome.services.ShomeGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ShomeParser extends AbstractAntlrParser {

	@Inject
	private ShomeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalShomeParser createParser(XtextTokenStream stream) {
		return new InternalShomeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Home";
	}

	public ShomeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ShomeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
