/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.smarthome.am.shome;

import fr.unice.polytech.si5.smarthome.am.shome.AbstractShomeRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ShomeRuntimeModule extends AbstractShomeRuntimeModule {
}
